# Generated by Django 4.2.14 on 2026-05-27 18:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "tenants",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="LocationMapping",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("canonical_name", models.CharField(max_length=255)),
                (
                    "canonical_location_code",
                    models.CharField(
                        help_text="Internal stable identifier, e.g. LOC-BER-01",
                        max_length=50,
                    ),
                ),
                (
                    "sap_plant_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sap_company_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "sap_cost_center",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "utility_account_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "utility_meter_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "travel_cost_center",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "travel_department_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "default_scope",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SCOPE_1", "Scope 1"),
                            ("SCOPE_2", "Scope 2"),
                            ("SCOPE_3", "Scope 3"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="location_mappings",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "location_mappings",
                "indexes": [
                    models.Index(
                        fields=["tenant", "sap_plant_code"],
                        name="location_ma_tenant__bbbf22_idx",
                    ),
                    models.Index(
                        fields=["tenant", "utility_account_number"],
                        name="location_ma_tenant__aead00_idx",
                    ),
                    models.Index(
                        fields=["tenant", "travel_cost_center"],
                        name="location_ma_tenant__c0822a_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="locationmapping",
            constraint=models.UniqueConstraint(
                fields=("tenant", "canonical_location_code"),
                name="unique_canonical_location_per_tenant",
            ),
        ),
    ]
