# Generated by Django 4.2.14 on 2026-05-27 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IngestionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("RUNNING", "Running"),
                            ("SUCCESS", "Success"),
                            ("PARTIAL_SUCCESS", "Partial Success"),
                            ("FAILED", "Failed"),
                            ("REVIEW_REQUIRED", "Review Required"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "raw_file",
                    models.FileField(
                        blank=True,
                        help_text="Original uploaded file for audit",
                        null=True,
                        upload_to="uploads/%Y/%m/%d/",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "api_request_log",
                    models.JSONField(
                        blank=True,
                        help_text="Query params, endpoint, timestamp for audit",
                        null=True,
                    ),
                ),
                ("records_fetched", models.PositiveIntegerField(blank=True, null=True)),
                ("records_failed", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "summary",
                    models.JSONField(
                        blank=True,
                        help_text="{total_rows: N, normalized_rows: M, flagged_rows: K}",
                        null=True,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ingestion_jobs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RawTravelRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_payload", models.JSONField()),
                ("expense_report_id", models.CharField(db_index=True, max_length=50)),
                ("employee_id", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "cost_center",
                    models.CharField(
                        blank=True, db_index=True, max_length=20, null=True
                    ),
                ),
                (
                    "department_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "travel_type",
                    models.CharField(
                        choices=[
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("GROUND", "Ground Transport"),
                            ("RAIL", "Rail"),
                            ("CAR_RENTAL", "Car Rental"),
                        ],
                        max_length=20,
                    ),
                ),
                ("trip_date", models.DateField(db_index=True)),
                ("origin", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "destination",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "origin_airport_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "destination_airport_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=20)),
                ("currency", models.CharField(max_length=3)),
                (
                    "booking_class",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "number_of_nights",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_travel_records",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_travel_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "raw_travel_records",
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="RawSAPRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_payload", models.JSONField()),
                ("purchase_order_id", models.CharField(db_index=True, max_length=20)),
                ("company_code", models.CharField(db_index=True, max_length=4)),
                (
                    "purchasing_organization",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("plant", models.CharField(db_index=True, max_length=4)),
                ("material", models.CharField(db_index=True, max_length=40)),
                (
                    "material_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "order_quantity",
                    models.DecimalField(decimal_places=3, max_digits=20),
                ),
                ("order_unit", models.CharField(max_length=10)),
                (
                    "net_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "document_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("creation_date", models.DateField(db_index=True)),
                ("supplier", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "supplier_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                (
                    "checksum",
                    models.CharField(
                        db_index=True,
                        help_text="SHA-256 of raw_payload for deduplication",
                        max_length=64,
                    ),
                ),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_sap_records",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_sap_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "raw_sap_records",
                "ordering": ["-fetched_at"],
            },
        ),
        migrations.CreateModel(
            name="IngestionSource",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable, e.g. 'SAP Production'",
                        max_length=255,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_ODATA", "SAP OData V4"),
                            ("UTILITY_CSV", "Utility CSV Upload"),
                            ("TRAVEL_API", "Travel API"),
                            ("TRAVEL_CSV", "Travel CSV Upload"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("api_endpoint", models.URLField(blank=True, null=True)),
                (
                    "api_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "api_password_encrypted",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "api_headers",
                    models.JSONField(
                        blank=True,
                        help_text="Extra headers, e.g. x-csrf-token",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingestion_sources",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_sources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jobs",
                to="ingestion.ingestionsource",
            ),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingestion_jobs",
                to="core.tenant",
            ),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="triggered_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="RawUtilityRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("raw_payload", models.JSONField()),
                ("account_number", models.CharField(db_index=True, max_length=50)),
                (
                    "meter_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, null=True
                    ),
                ),
                (
                    "utility_type",
                    models.CharField(
                        choices=[
                            ("ELECTRICITY", "Electricity"),
                            ("NATURAL_GAS", "Natural Gas"),
                            ("WATER", "Water"),
                            ("STEAM", "Steam"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("billing_period_start", models.DateField()),
                ("billing_period_end", models.DateField()),
                ("consumption", models.DecimalField(decimal_places=3, max_digits=20)),
                ("consumption_unit", models.CharField(max_length=10)),
                (
                    "total_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "cost_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("tariff_code", models.CharField(blank=True, max_length=50, null=True)),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
                ("checksum", models.CharField(db_index=True, max_length=64)),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_utility_records",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_utility_records",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "raw_utility_records",
                "ordering": ["-fetched_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "account_number", "billing_period_start"],
                        name="raw_utility_tenant__dfa93f_idx",
                    ),
                    models.Index(
                        fields=["ingestion_job", "meter_id"],
                        name="raw_utility_ingesti_c70d5a_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="rawutilityrecord",
            constraint=models.UniqueConstraint(
                fields=(
                    "ingestion_job",
                    "account_number",
                    "meter_id",
                    "billing_period_start",
                ),
                name="unique_utility_reading_per_job",
            ),
        ),
        migrations.AddIndex(
            model_name="rawtravelrecord",
            index=models.Index(
                fields=["tenant", "cost_center", "trip_date"],
                name="raw_travel__tenant__f3f6f4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawtravelrecord",
            index=models.Index(
                fields=["ingestion_job", "expense_report_id"],
                name="raw_travel__ingesti_0acea6_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawtravelrecord",
            constraint=models.UniqueConstraint(
                fields=("ingestion_job", "expense_report_id"),
                name="unique_expense_per_job",
            ),
        ),
        migrations.AddIndex(
            model_name="rawsaprecord",
            index=models.Index(
                fields=["tenant", "company_code", "plant"],
                name="raw_sap_rec_tenant__f9d1d2_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawsaprecord",
            index=models.Index(
                fields=["ingestion_job", "purchase_order_id"],
                name="raw_sap_rec_ingesti_678618_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="rawsaprecord",
            index=models.Index(
                fields=["tenant", "material", "creation_date"],
                name="raw_sap_rec_tenant__781817_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="rawsaprecord",
            constraint=models.UniqueConstraint(
                fields=("ingestion_job", "purchase_order_id"), name="unique_po_per_job"
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(
                fields=["tenant", "status", "created_at"],
                name="ingestion_j_tenant__a22b4a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="ingestionjob",
            index=models.Index(
                fields=["source", "status"], name="ingestion_j_source__2c1b62_idx"
            ),
        ),
    ]
