# Generated by Django 4.2.14 on 2026-05-27 18:33

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NormalizedActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP_PROCUREMENT", "SAP Procurement"),
                            ("UTILITY_ELECTRICITY", "Utility Electricity"),
                            ("UTILITY_GAS", "Utility Gas"),
                            ("UTILITY_WATER", "Utility Water"),
                            ("TRAVEL_FLIGHT", "Travel Flight"),
                            ("TRAVEL_HOTEL", "Travel Hotel"),
                            ("TRAVEL_GROUND", "Travel Ground"),
                            ("TRAVEL_RAIL", "Travel Rail"),
                        ],
                        max_length=30,
                    ),
                ),
                ("activity_date", models.DateField(db_index=True)),
                (
                    "scope_category",
                    models.CharField(
                        choices=[
                            ("SCOPE_1", "Scope 1"),
                            ("SCOPE_2", "Scope 2"),
                            ("SCOPE_3", "Scope 3"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "activity_category",
                    models.CharField(
                        choices=[
                            ("STATIONARY_COMBUSTION", "Stationary Combustion"),
                            ("MOBILE_COMBUSTION", "Mobile Combustion"),
                            ("PURCHASED_ELECTRICITY", "Purchased Electricity"),
                            ("PURCHASED_HEAT", "Purchased Heat / Steam"),
                            ("PURCHASED_COOLING", "Purchased Cooling"),
                            ("BUSINESS_TRAVEL_AIR", "Business Travel — Air"),
                            ("BUSINESS_TRAVEL_HOTEL", "Business Travel — Hotel"),
                            ("BUSINESS_TRAVEL_GROUND", "Business Travel — Ground"),
                            ("BUSINESS_TRAVEL_RAIL", "Business Travel — Rail"),
                            ("PURCHASED_GOODS", "Purchased Goods & Services"),
                            ("WASTE", "Waste"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=20,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("quantity_unit", models.CharField(max_length=10)),
                (
                    "emission_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="kg CO2e per quantity_unit",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "emission_factor_source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. DEFRA 2024, EPA GHG Emission Factors Hub",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "co2e_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=20,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "spend_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "spend_currency",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending Review"),
                            ("FLAGGED", "Flagged — Needs Attention"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("LOCKED_FOR_AUDIT", "Locked for Audit"),
                        ],
                        db_index=True,
                        default="PENDING_REVIEW",
                        max_length=20,
                    ),
                ),
                (
                    "flag_reason",
                    models.CharField(
                        blank=True,
                        help_text="Auto-populated by normalizer or analyst",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("analyst_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("version", models.PositiveIntegerField(default=1)),
                (
                    "change_reason",
                    models.TextField(
                        blank=True,
                        help_text="Why was this row edited? Required for audit.",
                        null=True,
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "canonical_location",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if location could not be mapped — analyst must resolve",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_activities",
                        to="core.locationmapping",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deleted_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ingestion_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_activities",
                        to="ingestion.ingestionjob",
                    ),
                ),
                (
                    "previous_version",
                    models.ForeignKey(
                        blank=True,
                        help_text="Points to the previous version if this row was edited",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="next_versions",
                        to="activities.normalizedactivity",
                    ),
                ),
                (
                    "raw_sap_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_activities",
                        to="ingestion.rawsaprecord",
                    ),
                ),
                (
                    "raw_travel_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_activities",
                        to="ingestion.rawtravelrecord",
                    ),
                ),
                (
                    "raw_utility_record",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="normalized_activities",
                        to="ingestion.rawutilityrecord",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="normalized_activities",
                        to="core.tenant",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "normalized_activities",
                "ordering": ["-activity_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATED", "Created"),
                            ("UPDATED", "Updated"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("FLAGGED", "Flagged"),
                            ("LOCKED", "Locked for Audit"),
                            ("UNLOCKED", "Unlocked from Audit"),
                            ("DELETED", "Soft Deleted"),
                            ("RESTORED", "Restored"),
                        ],
                        max_length=20,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "snapshot",
                    models.JSONField(
                        help_text="Full serialized state of the activity at the time of action"
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="activities.normalizedactivity",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_logs",
                        to="core.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "activity_audit_logs",
                "ordering": ["-performed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="normalizedactivity",
            index=models.Index(
                fields=["tenant", "status", "activity_date"],
                name="normalized__tenant__0b781a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedactivity",
            index=models.Index(
                fields=["tenant", "scope_category", "activity_category"],
                name="normalized__tenant__afd4b3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedactivity",
            index=models.Index(
                fields=["canonical_location", "activity_date"],
                name="normalized__canonic_25a1c9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedactivity",
            index=models.Index(
                fields=["tenant", "source_type", "status"],
                name="normalized__tenant__dff714_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="normalizedactivity",
            index=models.Index(
                fields=["ingestion_job", "status"],
                name="normalized__ingesti_df2adf_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="normalizedactivity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(
                        ("raw_sap_record__isnull", False),
                        ("raw_travel_record__isnull", True),
                        ("raw_utility_record__isnull", True),
                    ),
                    models.Q(
                        ("raw_sap_record__isnull", True),
                        ("raw_travel_record__isnull", True),
                        ("raw_utility_record__isnull", False),
                    ),
                    models.Q(
                        ("raw_sap_record__isnull", True),
                        ("raw_travel_record__isnull", False),
                        ("raw_utility_record__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_raw_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="normalizedactivity",
            constraint=models.CheckConstraint(
                check=models.Q(
                    (
                        "status__in",
                        ["PENDING_REVIEW", "FLAGGED", "APPROVED", "REJECTED"],
                    ),
                    ("co2e_kg__isnull", False),
                    _connector="OR",
                ),
                name="locked_requires_co2e",
            ),
        ),
        migrations.AddIndex(
            model_name="activityauditlog",
            index=models.Index(
                fields=["tenant", "activity", "-performed_at"],
                name="activity_au_tenant__d7deae_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="activityauditlog",
            index=models.Index(
                fields=["performed_by", "-performed_at"],
                name="activity_au_perform_4cfff7_idx",
            ),
        ),
    ]
